# Joint state controller

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

doosan_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Joint1
    - Joint2
    - Joint3
    - Joint4
  gains:
    Joint1: {p: 1.0, i: 0.0, d: 0.0}
    Joint2: {p: 1.0, i: 0.0, d: 0.0}
    Joint3: {p: 1.0, i: 0.0, d: 0.0}
    Joint4: {p: 1.0, i: 0.0, d: 0.0}

joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint1
  pid: {p: 1.0, i: 0.0, d: 0.0}

joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint2
  pid: {p: 1.0, i: 0.0, d: 0.0}

joint3_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint3
  pid: {p: 1.0, i: 0.0, d: 0.0}

joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: Joint4
  pid: {p: 1.0, i: 0.0, d: 0.0}